// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var SHOPIFY_URL = "https://qqn01v-hw.myshopify.com/api/2025-07/graphql.json";
var SHOPIFY_TOKEN = "a7d13cd4d2b2db881f5d07e70855125f";
var QUERY = `
  query ListProducts($first: Int!) {
    products(first: $first) {
      edges {
        node {
          id
          title
          handle
          description
          priceRange {
            minVariantPrice { amount currencyCode }
          }
          images(first: 1) { edges { node { url } } }
        }
      }
    }
  }
`;
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List personalized storybook products available in the My Star Stories shop, with title, handle, price, and description.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of products to return (1-50).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ limit }) => {
    const res = await fetch(SHOPIFY_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": SHOPIFY_TOKEN
      },
      body: JSON.stringify({ query: QUERY, variables: { first: limit } })
    });
    if (!res.ok) {
      return {
        content: [
          { type: "text", text: `Shopify request failed: ${res.status}` }
        ],
        isError: true
      };
    }
    const data = await res.json();
    const products = data?.data?.products?.edges?.map((e) => ({
      title: e.node.title,
      handle: e.node.handle,
      url: `https://mestar.pro/product/${e.node.handle}`,
      price: `${e.node.priceRange.minVariantPrice.amount} ${e.node.priceRange.minVariantPrice.currencyCode}`,
      description: e.node.description,
      image: e.node.images?.edges?.[0]?.node?.url ?? null
    })) ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var SHOPIFY_URL2 = "https://qqn01v-hw.myshopify.com/api/2025-07/graphql.json";
var SHOPIFY_TOKEN2 = "a7d13cd4d2b2db881f5d07e70855125f";
var QUERY2 = `
  query GetProduct($handle: String!) {
    productByHandle(handle: $handle) {
      id
      title
      handle
      description
      priceRange { minVariantPrice { amount currencyCode } }
      images(first: 5) { edges { node { url altText } } }
      variants(first: 20) {
        edges {
          node {
            id
            title
            availableForSale
            price { amount currencyCode }
            selectedOptions { name value }
          }
        }
      }
    }
  }
`;
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch full details for a single My Star Stories product by its Shopify handle (slug).",
  inputSchema: {
    handle: z2.string().min(1).describe("The product handle / slug, e.g. 'personalized-storybook'.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ handle }) => {
    const res = await fetch(SHOPIFY_URL2, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Storefront-Access-Token": SHOPIFY_TOKEN2
      },
      body: JSON.stringify({ query: QUERY2, variables: { handle } })
    });
    if (!res.ok) {
      return {
        content: [
          { type: "text", text: `Shopify request failed: ${res.status}` }
        ],
        isError: true
      };
    }
    const data = await res.json();
    const p = data?.data?.productByHandle;
    if (!p) {
      return {
        content: [{ type: "text", text: `Product not found: ${handle}` }],
        isError: true
      };
    }
    const product = {
      title: p.title,
      handle: p.handle,
      url: `https://mestar.pro/product/${p.handle}`,
      description: p.description,
      price: `${p.priceRange.minVariantPrice.amount} ${p.priceRange.minVariantPrice.currencyCode}`,
      images: p.images.edges.map((e) => e.node.url),
      variants: p.variants.edges.map((e) => ({
        id: e.node.id,
        title: e.node.title,
        available: e.node.availableForSale,
        price: `${e.node.price.amount} ${e.node.price.currencyCode}`,
        options: e.node.selectedOptions
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/get-order-status.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var get_order_status_default = defineTool3({
  name: "get_order_status",
  title: "Get order status",
  description: "Look up the status of a My Star Stories personalized storybook order by its order ID. Returns child name, story title, status, whether it has an audiobook, and (once ready) the PDF download URL.",
  inputSchema: {
    order_id: z3.string().uuid().describe("The order UUID returned when the order was placed.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ order_id }) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY;
    if (!supabaseUrl || !anonKey) {
      return {
        content: [
          { type: "text", text: "Backend is not configured." }
        ],
        isError: true
      };
    }
    const res = await fetch(
      `${supabaseUrl}/functions/v1/get-order-status`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${anonKey}`,
          apikey: anonKey
        },
        body: JSON.stringify({ order_id })
      }
    );
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [
          { type: "text", text: `Order lookup failed (${res.status}): ${text}` }
        ],
        isError: true
      };
    }
    let parsed;
    try {
      parsed = JSON.parse(text);
    } catch {
      parsed = text;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(parsed, null, 2) }],
      structuredContent: typeof parsed === "object" && parsed !== null ? parsed : { result: parsed }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "my-star-stories-mcp",
  title: "My Star Stories",
  version: "0.1.0",
  instructions: "Tools for the My Star Stories personalized children's storybook shop. Use `list_products` to browse the catalog, `get_product` for full details on a specific product by handle, and `get_order_status` to check the progress of a placed order by its UUID.",
  tools: [list_products_default, get_product_default, get_order_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
