// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list_products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/shopify.ts
var LOCAL_VARIANT_ID = "gid://mestar/ProductVariant/personalized-storybook";
var LOCAL_PRODUCTS = [
  {
    node: {
      id: "gid://mestar/Product/personalized-storybook",
      title: "Personalized Storybook \u2014 Your Child Is the Star",
      description: "A one-of-a-kind digital PDF storybook starring your child. Upload a photo, choose a theme, and download a print-ready book plus matching coloring pages in minutes.",
      handle: "personalized-storybook",
      priceRange: {
        minVariantPrice: { amount: "19.99", currencyCode: "USD" }
      },
      images: {
        edges: [
          { node: { url: "/images/sample-page-1.jpg", altText: "Sample storybook page 1" } },
          { node: { url: "/images/sample-page-2.jpg", altText: "Sample storybook page 2" } },
          { node: { url: "/images/sample-page-3.jpg", altText: "Sample storybook page 3" } },
          { node: { url: "/images/sample-page-4.jpg", altText: "Sample storybook page 4" } }
        ]
      },
      variants: {
        edges: [
          {
            node: {
              id: LOCAL_VARIANT_ID,
              title: "Default",
              price: { amount: "19.99", currencyCode: "USD" },
              availableForSale: true,
              selectedOptions: [{ name: "Format", value: "Digital PDF" }]
            }
          }
        ]
      },
      options: [{ name: "Format", values: ["Digital PDF"] }]
    }
  }
];
async function fetchProducts(_first = 20) {
  return LOCAL_PRODUCTS;
}
async function fetchProductByHandle(handle) {
  return LOCAL_PRODUCTS.find((p) => p.node.handle === handle) ?? null;
}

// src/lib/mcp/tools/list_products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List MeStar's public product catalog (personalized digital storybooks and add-ons) with title, price, handle, and description.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const products = await fetchProducts();
    const simplified = products.map((p) => ({
      id: p.node.id,
      title: p.node.title,
      handle: p.node.handle,
      description: p.node.description,
      price: `${p.node.priceRange.minVariantPrice.amount} ${p.node.priceRange.minVariantPrice.currencyCode}`,
      url: `https://mestar.pro/product/${p.node.handle}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(simplified, null, 2) }],
      structuredContent: { products: simplified }
    };
  }
});

// src/lib/mcp/tools/get_product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Get full public details for a single MeStar product by its URL handle (e.g. 'personalized-storybook').",
  inputSchema: {
    handle: z.string().min(1).describe("Product handle from the product URL, e.g. 'personalized-storybook'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ handle }) => {
    const product = await fetchProductByHandle(handle);
    if (!product) {
      return {
        content: [{ type: "text", text: `No product found with handle: ${handle}` }],
        isError: true
      };
    }
    const p = product.node;
    const details = {
      id: p.id,
      title: p.title,
      handle: p.handle,
      description: p.description,
      price: `${p.priceRange.minVariantPrice.amount} ${p.priceRange.minVariantPrice.currencyCode}`,
      images: p.images.edges.map((e) => e.node.url),
      options: p.options,
      url: `https://mestar.pro/product/${p.handle}`
    };
    return {
      content: [{ type: "text", text: JSON.stringify(details, null, 2) }],
      structuredContent: { product: details }
    };
  }
});

// src/lib/mcp/tools/list_themes.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var THEMES = [
  "Space Adventure",
  "Underwater Journey",
  "Dinosaur Discovery",
  "Fairy Tale Kingdom",
  "Superhero Origin",
  "Jungle Safari",
  "Magical Forest",
  "Pirate Quest",
  "Farm Animals",
  "Sports Champion",
  "Dance & Music",
  "Bedtime Dreams",
  "Birthday Celebration",
  "Winter Wonderland",
  "Ocean Rescue",
  "Robot Friends"
];
var list_themes_default = defineTool3({
  name: "list_story_themes",
  title: "List story themes",
  description: "List the story themes a customer can choose when personalizing a MeStar storybook.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: THEMES.join(", ") }],
    structuredContent: { themes: THEMES }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "mestar-mcp",
  title: "MeStar",
  version: "0.1.0",
  instructions: "Public tools for MeStar (mestar.pro), a personalized digital storybook shop. Use `list_products` to see the catalog, `get_product` for details on a specific product by handle, and `list_story_themes` for the story themes available during personalization. This server exposes only public catalog data \u2014 no customer, order, or account information.",
  tools: [list_products_default, get_product_default, list_themes_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
